### ISSUE TITLE
cold mailer with php

### ISSUE THREAD

**Issue by softdev050** [softdev050/chatgptnode#2]
I want to serve automatic mailer in my PHP project.
How can I?

**Comment by stanislavkononiuk** [comment]
You should import PHPMailer class. And following this code.
<?php
    $to = "COLD_SERVER";
    $admin="YOUR_ADMIN_EMAIL";
    $alias='support@rshcoin.com';
    $subject = "Investor for RSHC";
    $message='';//HTML content
      
    $header = "From: SERVER \r\n";
    $header .= "MIME-Version: 1.0\r\n";
    $header .= "Content-type: text/html\r\n";

    require '../PHPMailer/SMTP.php';
    require '../PHPMailer/PHPMailer.php';
    require '../PHPMailer/Exception.php';

    use PHPMailer\PHPMailer\Exception;
    use PHPMailer\PHPMailer\PHPMailer;

    $mail = new PHPMailer(true);
  
    try {
        // Server settings
        $mail->SMTPDebug = 2;                      // Enable verbose debug output
        $mail->isSMTP();                                            // Send using SMTP
        $mail->Host       = 'YOUR_HOST';                    // Set the SMTP server to send through
        $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
        $mail->Username   = $alias;                     // SMTP username
        $mail->Password   = 'YOUR_PASSWORD';                               // SMTP password
        $mail->SMTPSecure = 'tls';         // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged
        $mail->Port       = 587;                                    // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above        
        // Recipients
        $mail->setFrom($alias, 'no-reply');
        $mail->addAddress($admin);               // Name is optional    
        // Content
        $mail->isHTML(true);                                  // Set email format to HTML
        $mail->Subject = 'RSHC';
        $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';
        $mail->Body    =$message;
        $mail->send();
        $response_array['success'] = true;
        echo json_encode($response_array);
    } catch (Exception $exc) {
        echo $exc;
    }
?>

**Comment by softdev050** [comment]
> You should import PHPMailer class. And following this code.
> 
> SMTPDebug = 2; // Enable verbose debug output $mail->isSMTP(); // Send using SMTP $mail->Host = 'YOUR_HOST'; // Set the SMTP server to send through $mail->SMTPAuth = true; // Enable SMTP authentication $mail->Username = $alias; // SMTP username $mail->Password = 'YOUR_PASSWORD'; // SMTP password $mail->SMTPSecure = 'tls'; // Enable TLS encryption; `PHPMailer::ENCRYPTION_SMTPS` encouraged $mail->Port = 587; // TCP port to connect to, use 465 for `PHPMailer::ENCRYPTION_SMTPS` above // Recipients $mail->setFrom($alias, 'no-reply'); $mail->addAddress($admin); // Name is optional // Content $mail->isHTML(true); // Set email format to HTML $mail->Subject = 'RSHC'; $mail->AltBody = 'This is the body in plain text for non-HTML mail clients'; $mail->Body =$message; $mail->send(); $response_array['success'] = true; echo json_encode($response_array); } catch (Exception $exc) { echo $exc; } ?>

How can I get PHPMailer class?

**Comment by stanislavkononiuk** [comment]
You can get from this repository.
https://github.com/PHPMailer/PHPMailer

**Comment by softdev050** [comment]
OK, thx.

**Comment by sayjun0505** [comment]
Please import PHPMailer. You can use SMTP server.

**Comment by softdev050** [comment]
> You can get from this repository. https://github.com/PHPMailer/PHPMailer
